# Netlify Configuration for OCT POS Frontend
# Based on official Netlify Vite documentation

[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA redirect rule - serves index.html for all routes to avoid 404s
# This is essential for React Router and other SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache optimization for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure index.html is not cached for updates
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
